name: Lint and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install python dependencies
      run: python -m pip install -r requirements-dev.txt
    - name: Install c++ dependencies
      run: sudo apt-get install clang-format clang-tidy build-essential cmake
    - name: Test python and c++
      run: make test
    - name: Lint check
      run: make lint_check
